### ISSUE TITLE
Errors submitting proposals

### ISSUE THREAD

**Issue by gavindoughtie** [DA0-DA0/cw-dao-dapp#29]
This is with the update_local.sh running; both on the main branch and in proposals-display. I created a second account and sent it some stake from the initial account thinking it was the account 0 issue we were talking about last week.

```Error when broadcasting tx E63AABBA1D654D4A98FD2E50D6B8EBD94F8D815BBAB47EACC8C22D0160BF64BC at height 12786. Code: 5; Raw log: github.com/CosmWasm/wasmd/x/wasm/keeper.Keeper.execute github.com/CosmWasm/wasmd/x/wasm/keeper/keeper.go:354 github.com/CosmWasm/wasmd/x/wasm/keeper.PermissionedKeeper.Execute github.com/CosmWasm/wasmd/x/wasm/keeper/contract_keeper.go:48 github.com/CosmWasm/wasmd/x/wasm/keeper.msgServer.ExecuteContract github.com/CosmWasm/wasmd/x/wasm/keeper/msg_server.go:91 github.com/CosmWasm/wasmd/x/wasm.NewHandler.func1 github.com/CosmWasm/wasmd/x/wasm/handler.go:31 github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs github.com/cosmos/cosmos-sdk@v0.42.10/baseapp/baseapp.go:724 github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx github.com/cosmos/cosmos-sdk@v0.42.10/baseapp/baseapp.go:669 github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).DeliverTx github.com/cosmos/cosmos-sdk@v0.42.10/baseapp/abci.go:273 github.com/tendermint/tendermint/abci/client.(*localClient).DeliverTxAsync github.com/tendermint/tendermint@v0.34.13/abci/client/local_client.go:95 github.com/tendermint/tendermint/proxy.(*appConnConsensus).DeliverTxAsync github.com/tendermint/tendermint@v0.34.13/proxy/app_conn.go:85 github.com/tendermint/tendermint/state.execBlockOnProxyApp github.com/tendermint/tendermint@v0.34.13/state/execution.go:320 github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock github.com/tendermint/tendermint@v0.34.13/state/execution.go:140 github.com/tendermint/tendermint/consensus.(*State).finalizeCommit github.com/tendermint/tendermint@v0.34.13/consensus/state.go:1635 github.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit github.com/tendermint/tendermint@v0.34.13/consensus/state.go:1546 github.com/tendermint/tendermint/consensus.(*State).enterCommit.func1 github.com/tendermint/tendermint@v0.34.13/consensus/state.go:1481 github.com/tendermint/tendermint/consensus.(*State).enterCommit github.com/tendermint/tendermint@v0.34.13/consensus/state.go:1519 github.com/tendermint/tendermint/consensus.(*State).addVote github.com/tendermint/tendermint@v0.34.13/consensus/state.go:2132 github.com/tendermint/tendermint/consensus.(*State).tryAddVote github.com/tendermint/tendermint@v0.34.13/consensus/state.go:1930 github.com/tendermint/tendermint/consensus.(*State).handleMsg github.com/tendermint/tendermint@v0.34.13/consensus/state.go:838 github.com/tendermint/tendermint/consensus.(*State).receiveRoutine github.com/tendermint/tendermint@v0.34.13/consensus/state.go:782 failed to execute message; message index: 0: Unauthorized: execute wasm contract failed```

**Comment by gavindoughtie** [comment]
FYI after fixing the memo field in my latest PR I still see:
```
Error when broadcasting tx 18DE5880EDB7332998402671FB1D7D9664B1108DBBF542D5D2F59E249BD79733 at height 16314. Code: 5; Raw log: github.com/CosmWasm/wasmd/x/wasm/keeper.Keeper.execute github.com/CosmWasm/wasmd/x/wasm/keeper/keeper.go:354 github.com/CosmWasm/wasmd/x/wasm/keeper.PermissionedKeeper.Execute github.com/CosmWasm/wasmd/x/wasm/keeper/contract_keeper.go:48 github.com/CosmWasm/wasmd/x/wasm/keeper.msgServer.ExecuteContract github.com/CosmWasm/wasmd/x/wasm/keeper/msg_server.go:91 github.com/CosmWasm/wasmd/x/wasm.NewHandler.func1 github.com/CosmWasm/wasmd/x/wasm/handler.go:31 github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs github.com/cosmos/cosmos-sdk@v0.42.10/baseapp/baseapp.go:724 github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx github.com/cosmos/cosmos-sdk@v0.42.10/baseapp/baseapp.go:669 github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).DeliverTx github.com/cosmos/cosmos-sdk@v0.42.10/baseapp/abci.go:273 github.com/tendermint/tendermint/abci/client.(*localClient).DeliverTxAsync github.com/tendermint/tendermint@v0.34.13/abci/client/local_client.go:95 github.com/tendermint/tendermint/proxy.(*appConnConsensus).DeliverTxAsync github.com/tendermint/tendermint@v0.34.13/proxy/app_conn.go:85 github.com/tendermint/tendermint/state.execBlockOnProxyApp github.com/tendermint/tendermint@v0.34.13/state/execution.go:320 github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock github.com/tendermint/tendermint@v0.34.13/state/execution.go:140 github.com/tendermint/tendermint/consensus.(*State).finalizeCommit github.com/tendermint/tendermint@v0.34.13/consensus/state.go:1635 github.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit github.com/tendermint/tendermint@v0.34.13/consensus/state.go:1546 github.com/tendermint/tendermint/consensus.(*State).enterCommit.func1 github.com/tendermint/tendermint@v0.34.13/consensus/state.go:1481 github.com/tendermint/tendermint/consensus.(*State).enterCommit github.com/tendermint/tendermint@v0.34.13/consensus/state.go:1519 github.com/tendermint/tendermint/consensus.(*State).addVote github.com/tendermint/tendermint@v0.34.13/consensus/state.go:2132 github.com/tendermint/tendermint/consensus.(*State).tryAddVote github.com/tendermint/tendermint@v0.34.13/consensus/state.go:1930 github.com/tendermint/tendermint/consensus.(*State).handleMsg github.com/tendermint/tendermint@v0.34.13/consensus/state.go:838 github.com/tendermint/tendermint/consensus.(*State).receiveRoutine github.com/tendermint/tendermint@v0.34.13/consensus/state.go:782 failed to execute message; message index: 0: Unauthorized: execute wasm contract failed
```

**Comment by JakeHartnell** [comment]
> FYI after fixing the memo field in my latest PR I still see:
> 
> ```
> Error when broadcasting tx 18DE5880EDB7332998402671FB1D7D9664B1108DBBF542D5D2F59E249BD79733 at height 16314. Code: 5; Raw log: github.com/CosmWasm/wasmd/x/wasm/keeper.Keeper.execute github.com/CosmWasm/wasmd/x/wasm/keeper/keeper.go:354 github.com/CosmWasm/wasmd/x/wasm/keeper.PermissionedKeeper.Execute github.com/CosmWasm/wasmd/x/wasm/keeper/contract_keeper.go:48 github.com/CosmWasm/wasmd/x/wasm/keeper.msgServer.ExecuteContract github.com/CosmWasm/wasmd/x/wasm/keeper/msg_server.go:91 github.com/CosmWasm/wasmd/x/wasm.NewHandler.func1 github.com/CosmWasm/wasmd/x/wasm/handler.go:31 github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs github.com/cosmos/cosmos-sdk@v0.42.10/baseapp/baseapp.go:724 github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx github.com/cosmos/cosmos-sdk@v0.42.10/baseapp/baseapp.go:669 github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).DeliverTx github.com/cosmos/cosmos-sdk@v0.42.10/baseapp/abci.go:273 github.com/tendermint/tendermint/abci/client.(*localClient).DeliverTxAsync github.com/tendermint/tendermint@v0.34.13/abci/client/local_client.go:95 github.com/tendermint/tendermint/proxy.(*appConnConsensus).DeliverTxAsync github.com/tendermint/tendermint@v0.34.13/proxy/app_conn.go:85 github.com/tendermint/tendermint/state.execBlockOnProxyApp github.com/tendermint/tendermint@v0.34.13/state/execution.go:320 github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock github.com/tendermint/tendermint@v0.34.13/state/execution.go:140 github.com/tendermint/tendermint/consensus.(*State).finalizeCommit github.com/tendermint/tendermint@v0.34.13/consensus/state.go:1635 github.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit github.com/tendermint/tendermint@v0.34.13/consensus/state.go:1546 github.com/tendermint/tendermint/consensus.(*State).enterCommit.func1 github.com/tendermint/tendermint@v0.34.13/consensus/state.go:1481 github.com/tendermint/tendermint/consensus.(*State).enterCommit github.com/tendermint/tendermint@v0.34.13/consensus/state.go:1519 github.com/tendermint/tendermint/consensus.(*State).addVote github.com/tendermint/tendermint@v0.34.13/consensus/state.go:2132 github.com/tendermint/tendermint/consensus.(*State).tryAddVote github.com/tendermint/tendermint@v0.34.13/consensus/state.go:1930 github.com/tendermint/tendermint/consensus.(*State).handleMsg github.com/tendermint/tendermint@v0.34.13/consensus/state.go:838 github.com/tendermint/tendermint/consensus.(*State).receiveRoutine github.com/tendermint/tendermint@v0.34.13/consensus/state.go:782 failed to execute message; message index: 0: Unauthorized: execute wasm contract failed
> ```

Intersting, after fixing the memo it worked for me...

**Comment by gavindoughtie** [comment]
This appears to all just be related to the "account 0" issue with Keplr, so closing for now.
