### ISSUE TITLE
Don't show JSON on text proposal voting page

### ISSUE THREAD

**Issue by JakeHartnell** [DA0-DA0/cw-dao-dapp#30]
![hide_json_on_text_proposals](https://user-images.githubusercontent.com/521978/139559760-e9093f10-2ea0-4d54-b16c-086b045cf982.png)

**Comment by gavindoughtie** [comment]
I want to do a whole revamp of proposal and message rendering for proposals. It would be akin to the memo generation function I added to proposal.

**Comment by JakeHartnell** [comment]
> I want to do a whole revamp of proposal and message rendering for proposals. It would be akin to the memo generation function I added to proposal.

Maybe should wait on some designs for this. :thinking:

**Comment by gavindoughtie** [comment]
JSON content no longer appears if it is not present in the message.
